services:
  kukey:
    image: hd0rable/kukey:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - PROD_DB_URL=${PROD_DB_URL}
      - PROD_DB_USERNAME=${PROD_DB_USERNAME}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SECRET_API_KEY=${SECRET_API_KEY}
      - SPRING_PROFILES_ACTIVE=prod,prod-db,prod-port,common
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DISCORD_URL=${DISCORD_URL}
      - BUKET_NAME=${BUKET_NAME}
      - TZ=Asia/Seoul