spring:
  application:
    name: kukey
  profiles:
    group:
      local : local-db, local-port, common
      prod: prod-db, prod-port, common
    active: local
  web:
    resources:
      add-mappings: false
---
# 로컬용 DB
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
---
# 배포용 DB
spring:
  config:
    activate:
      on-profile: prod-db
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
---
# 로컬용 포트
spring:
  config:
    activate:
      on-profile: local-port
server:
  port: 8080
---
# 배포용 포트
spring:
  config:
    activate:
      on-profile: prod-port
server:
  port: 8080
---
# 공통 속성
spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 3MB # 개별 파일의 최대 크기
      max-request-size: 3MB # 전체 요청 크기

univcert:
  api:
    key: ${SECRET_API_KEY}

cloud:
  aws:
    s3:
      bucket: ${BUKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 259200000  #3일
  memory-access-token-expiration: 604800000 #7일

kukey:
  admin:
    id: ${ADMIN_ID}
    password: ${ADMIN_PASSWORD}

discord:
  name: discord-feign-client
  webhook-url: ${DISCORD_URL}